### ISSUE TITLE
after upgrade the plugin, the old http plugin still exist and not using new one

### ISSUE THREAD

**Issue by IzekChen** [logstash-plugins/logstash-input-http#91]
- Version: logstash6.3.0-1
- Operating System: redhat

Currently we are facing the issue https://github.com/logstash-plugins/logstash-input-http/issues/61 
I try to update the plugin with logstash-plugin
and it looks like this now
![image](https://user-images.githubusercontent.com/7790230/42873322-56833b74-8ab1-11e8-9203-0511627e115b.png)

it didnt remove the old plugin folder and not using the new one.
Then I try to use "logstash-plugin remove logstash-input-http", then it shows not plugin available

[2018-07-18T17:25:32,529][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:cert_info, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any input plugin named 'http'. Are you sure this is correct? Trying to load the http input plugin resulted in this error: no such file to load -- logstash/inputs/http", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:210:in `lookup_pipeline_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/plugin_factory.rb:89:in `plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:110:in `plugin'", "(eval):8:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:82:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:167:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:305:in `block in converge_state'"]}

**Comment by robbavey** [comment]
Can you run this command and tell me what the output is: 

```
bin/logstash-plugin list --verbose | grep http
```
